<?php $groups = $this->getUsersInLeague(); ?>
<?php $cardData = json_encode($this->CreateCollection()); ?>
<?php $url = $this->getUrl('*/*/data'); ?>
<button class="submit_button" id="sendDataButton">Submit</button>
<div class=" cards" style="display: ruby-text;"></div>


<script>
var sendDataUrl = '<?php echo $this->getUrl('*/*/data'); ?>';
var bonusArrayString = '<?php echo Mage::getStoreConfig('salesman/bonus/amount'); ?>';
document.observe("dom:loaded", function() {
    var cards = new createCards('<?php print_r($cardData); ?>', '<?php echo $groups; ?>',
        '<?php echo $url; ?>');
})
</script>